FROM centos:6
MAINTAINER hfm.garden@gmail.com

RUN yum -q -y install epel-release
RUN yum -q -y install rpmdevtools yum-utils

RUN rpmdev-setuptree

run wget -nv http://imagemagick.org/download/linux/SRPMS/releases/ImageMagick-6.5.4-10.src.rpm -O /root/rpmbuild/SRPMS/ImageMagick-6.5.4-10.src.rpm
RUN yum-builddep -y --nogpgcheck /root/rpmbuild/SRPMS/ImageMagick-6.5.4-10.src.rpm
RUN rpmbuild --rebuild /root/rpmbuild/SRPMS/ImageMagick-6.5.4-10.src.rpm
