_common_: &common
  build: .
  command: cp -a /root/rpmbuild/RPMS/x86_64 /tmp/ImageMagick
  volumes:
    - .:/tmp:rw

centos5:
  <<: *common
  dockerfile: Dockerfile.centos5

centos6:
  <<: *common
  dockerfile: Dockerfile.centos6
